### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by composerinteralia** [rubocop-hq/rubocop-performance#10]
It looks like RuboCop runs on both Travis and CI. Do we know why that is? I'm assuming we can just run on Circle using a configuration like https://github.com/rubocop-hq/rubocop-rspec/blob/master/.circleci/config.yml

We don't quite have everything set up yet (rubocop tasks, documentation tasks, etc.), but we can at least get the specs running.

In the gemspec I put the required Ruby version as `<= 2.3` (2.2 is no longer supported), so I think we can run against 2.3 and higher.

**Comment by bbatsov** [comment]
We're in the process of migrating from Travis to Circle. We keep both running for a while until we're confident in the Circle setup. You should setup only Circle.
