### ISSUE TITLE
False positive with DeletePrefix

### ISSUE THREAD

**Issue by avdv** [rubocop-hq/rubocop-performance#118]
For a multi-line string, I am using `gsub(/^  /, '')` and I receive a wrong suggestion that I should replace this call with `delete_prefix`.

Note that `^` matches at the beginning of a line, not only at the beginning of the string.
 
--------

## Expected behavior

No offense being reported.

## Actual behavior

```
lib/colorls/flags.rb:169:23: C: Performance/DeletePrefix: Use delete_prefix instead of gsub.

      puts <<EXAMPLES.gsub(/^  /, '')

                      ^^^^
```

## Steps to reproduce the problem

```
def show_examples
      puts <<EXAMPLES.gsub(/^  /, '')

  examples:

    * show the given file:

      colorls README.md

    * show matching files and list matching directories:

EXAMPLES
    end
```

## RuboCop version

```
0.84.0 (using Parser 2.7.1.2, rubocop-ast 0.0.3, running on ruby 2.6.6 x86_64-linux)
```

**Comment by mattbrictson** [comment]
I believe the same bug exists for `Performance/StartWith`.

```ruby
# This checks that _any_ line in the output starts with "origin"
`git remote -v`.match?(/^origin/)

#  Performance/StartWith suggests this, which only tests the first line
`git remote -v`.start_with?("origin")
```

**Comment by mattbrictson** [comment]
I think the fix is that both cops should only flag patterns that start with `\A` (not `^`).

**Comment by avdv** [comment]
> I think the fix is that both cops should only flag patterns that start with `\A` (not `^`).

Yes, same goes for `$` and `\Z` in regard to the delete suffix and end with cops.
