### ISSUE TITLE
Add default configuration

### ISSUE THREAD

**Issue by composerinteralia** [rubocop-hq/rubocop-performance#14]
Import the default configuration from 
https://github.com/rubocop-hq/rubocop/blob/69fe5d22e09e6d6250331e9d0a38a27fbf9bdfc8/config/default.yml#L1660
and
https://github.com/rubocop-hq/rubocop/blob/69fe5d22e09e6d6250331e9d0a38a27fbf9bdfc8/config/enabled.yml#L919

We also need a good way to load up the defaults. We could do something like what is in rubocop-rspec:
https://github.com/rubocop-hq/rubocop-rspec/blob/6b2ab090531d67673730584d26f62603bcdef5e4/lib/rubocop-rspec.rb#L26
https://github.com/rubocop-hq/rubocop-rspec/blob/6b2ab090531d67673730584d26f62603bcdef5e4/lib/rubocop/rspec/inject.rb

But perhaps maybe there is a way we can add some of this to rubocop directly. [rubocop-rails](https://github.com/rubocop-hq/rubocop-rails) is going to need something similar.

**Comment by bquorning** [comment]
I think duplicating rubocop-rspec’s hack would be short-sighted. We regularly run into issues with identically named cops in different namespaces, etc.

There is an old issue open on RuboCop about formalizing an extension API: https://github.com/rubocop-hq/rubocop/issues/3414 – I hope @backus will rejoin the discussion.

**Comment by koic** [comment]
I'd like to solve the problem with the following PRs until the better API is developed.

- https://github.com/rubocop-hq/rubocop-performance/pull/26
- https://github.com/rubocop-hq/rubocop-performance/pull/25

First of all, I'd like to aim for release similar to RuboCop RSpec. Thank you.

**Comment by koic** [comment]
I will close this issue because the purpose of adding the default configuration is solved.
