### ISSUE TITLE
`Performance/StringInclude` autocorrect is unsafe

### ISSUE THREAD

**Issue by beauraF** [rubocop-hq/rubocop-performance#145]
Hi,

New cop `Performance/StringInclude` introduced by #117 is unsafe when use with `--auto-correct`. 

1. It currently auto-corrects the usage of `match` and `=~`. But the return values between `match` or `=~` and `include?` are different. If the value is used, the behavior is altered.
2. `=~` doesn't raise an error in case of `nil =~ /foobar/`. Same, behavior is altered.

Two examples that broke in our codebase:
```ruby
search_by_street_address = params[:types] =~ /street_address/
@agenda_requested_in_config ||= method.match(/agenda/)
```

--- 

I think it should only fix `match?` and reserve `match` and `=~` in the case of `--auto-correct-all`. I don't know if you can make that distinction?

If not, maybe move this cop as unsafe? What do you think?

**Comment by viraptor** [comment]
Adding another edge case - `=~` works on symbols, but `.include?` doesn't:
```
irb(main):002:0> :foo =~ /o/
=> 1
irb(main):003:0> :foo.include?(/o/)
Traceback (most recent call last):
...
```

**Comment by eugeneius** [comment]
Note that `Performance/StartWith` and `Performance/EndWith`, which `Performance/StringInclude` was based on, have these problems too. The issue with nil receivers was previously reported in https://github.com/rubocop-hq/rubocop-performance/issues/50.
