### ISSUE TITLE
Suggest replacing `ary.max(n)` with `ary.sort.last(n)` and `ary.min(n)` with `ary.sort.first(n)` where n != 1

### ISSUE THREAD

**Issue by fatkodima** [rubocop-hq/rubocop-performance#195]
For `n == 1` there is already a cop https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/redundant_sort.rb which makes the code simpler and also faster.

### Benchmark
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  gem 'benchmark-ips'
  gem 'benchmark-memory'
end

ARR = (1..100).to_a

Benchmark.ips do |x|
  x.report('sort.last')   { ARR.sort.last(5) }
  x.report('max')         { ARR.max(5) }
  x.compare!
end

puts "********* MEMORY *********"

Benchmark.memory do |x|
  x.report('sort.last')   { ARR.sort.last(5) }
  x.report('max')         { ARR.max(5) }
  x.compare!
end
```

### Results
```
Warming up --------------------------------------
           sort.last    43.789k i/100ms
                 max    14.995k i/100ms
Calculating -------------------------------------
           sort.last    452.014k (± 3.2%) i/s -      2.277M in   5.042623s
                 max    149.323k (± 1.9%) i/s -    749.750k in   5.022869s

Comparison:
           sort.last:   452013.7 i/s
                 max:   149322.8 i/s - 3.03x  (± 0.00) slower

********* MEMORY *********
Calculating -------------------------------------
           sort.last   120.000  memsize (     0.000  retained)
                         3.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)
                 max   200.000  memsize (     0.000  retained)
                         1.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

Comparison:
           sort.last:        120 allocated
                 max:        200 allocated - 1.67x more
```

**Comment by koic** [comment]
These look like incompatible behaviour.

```console
% cat example.rb
p (1..100).to_a.sort.last(5)
p (1..100).to_a.max(5)


% ruby -v example.rb
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
[96, 97, 98, 99, 100]
[100, 99, 98, 97, 96]
```

**Comment by fatkodima** [comment]
Ah, yeah. Just noticed that ordering is explicitly stated in the documentation. Never relied on this feature before 😄

**Comment by marcandre** [comment]
You also made the mistake of testing on the pathological case (with ascending sorted data). Do a `to_a.shuffle` for your array buildup and the results are reversed (as they should; `sort` does more work for nothing so should be the slowest in general). If you do `to_a.reverse`, the results favor `max` even more (as it finds the final answer right from the start).

**Comment by marcandre** [comment]
FWIW, @koic's argument is correct but insufficient, because:
- we could still optimize `min(5)` with `sort.first(5)`
- running the test on `max(5)` vs `sort.last(5).reverse` on the pathological case still has `max` slowest

Notet that in general, you can't optimize `foo(n)` with `bar(n).baz(n)` for builtin methods. If you could, it's a bug in `foo`'s implementation!

**Comment by fatkodima** [comment]
@marcandre Agreed with you, obviously not fair test case for `max` 😄 

 > we could still optimize min(5) with sort.first(5)

👍 

> running the test on max(5) vs sort.last(5).reverse on the pathological case still has max slowest

but for shuffled data `max` is faster and I would personally prefer its conciseness even if it will be slower that other more verbose variant.

So, just for `min(5)` => `sort.first(5)` I think it is not worth it?

**Comment by marcandre** [comment]
> So, just for `min(5)` => `sort.first(5)` I think it is not worth it?

I was saying that koic's argument is not enough to discredit that, but mine is. It's definitely not an actual optimization.
