### ISSUE TITLE
Performance/ConstantRegexp with a constant defined in a subclass

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop-performance#205]
When a regexp depends on a constant defined in a subclass, neither of the fixes suggested by `Performance/ConstantRegexp` work:

```ruby
class C
  def self.regexp
    %r{foo #{self::BASE_PATTERN}}
  end
end

class X < C
  BASE_PATTERN = /bar/
end

class Y < C
  BASE_PATTERN = /baz/
end
```

If the pattern is change to use the `/o` modifier, the first time the method is triggered the regexp will be interpolated for both subclasses:

```ruby
X.regexp
=> /foo (?-mix:bar)/
Y.regexp
=> /foo (?-mix:bar)/
```

If the regexp is extracted to a constant, it needs to be duplicated in every subclass (and the regexp could be considerably more complicated than the example here).

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
rubocop -V
1.8.1 (using Parser 3.0.0.0, rubocop-ast 1.4.0, running on ruby 2.6.6 x86_64-darwin18)
  - rubocop-performance 1.9.2
  - rubocop-rails 2.9.1
  - rubocop-rspec 2.1.0
```

**Comment by marcandre** [comment]
It would be more efficient to cache the result.

One "correct" code should probably be:

```ruby
class C
  def self.regexp
    @regexp ||= %r{foo #{self::BASE_PATTERN}}
  end
end
```

Is that accepted by by ConstantRegexp?

Although this won't work from Ractors... (one should use my [`ractor_cache`](https://github.com/ractor-tools/ractor-cache) gem for that purpose).

Or maybe this would work?

```ruby
def self.inherited(base)
  # Use the `o` flag because `BASE_PATTERN` isn't defined yet
  base.class_eval "REGEXP = /foo #{self::BASE_PATTERN}/o"
end
```

**Comment by dvandersluis** [comment]
> One "correct" code should probably be:
> 
> ```ruby
> class C
>   def self.regexp
>     @regexp ||= %r{foo #{self::BASE_PATTERN}}
>   end
> end
> ```

I like this and changed my code to use this pattern, but it is still not accepted by the cop, no.

**Comment by marcandre** [comment]
I think that memoized regexp like that should be acceptable 👍
