### ISSUE TITLE
Documentation on ReadTheDocs does not work

### ISSUE THREAD

**Issue by mobilutz** [rubocop-hq/rubocop-performance#45]
## Expected behavior

Documentation should be available on ReadTheDocs

## Actual behavior

One sees a 404 error page.

## Steps to reproduce the problem

Go to https://rubocop-performance.readthedocs.io/

## RuboCop version

Not applicable.

**Comment by koic** [comment]
https://rubocop-performance.readthedocs.io has been published. Thanks for your feedback!
