### ISSUE TITLE
Syntax error auto-correcting `Performance/RegexpMatch`

### ISSUE THREAD

**Issue by dduugg** [rubocop-hq/rubocop-performance#55]
I'm getting a syntax error auto-correcting a `Performance/RegexpMatch` violation in the following method definition:

```ruby
def foo(id)
  if id.=~(/\./)
    'yes'
  else
    'no'
  end
end
```

## Expected behavior

I expect this to autocorrect to:
```ruby
def foo(id)
  if /\./.match?(id)
    'yes'
  else
    'no'
  end
end
```

## Actual behavior

The autocorrection has an extra `)`, leading to a syntax error:
```ruby
def foo(id)
  if /\./.match?(id))
    'yes'
  else
    'no'
  end
end
```

## Steps to reproduce the problem

Put the above snippet into a `foo.rb` file, then:
```
$ bundle exec rubocop foo.rb -a
Inspecting 1 file
E

Offenses:
foo.rb:4:6: C: [Corrected] Performance/RegexpMatch: Use match? instead of =~ when MatchData is not used.
  if id.=~(/\./)
     ^^^^^^^^^^^
foo.rb:7:21: E: Lint/Syntax: unexpected token tRPAREN
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
  if /\./.match?(id))
                    ^
foo.rb:9:3: W: Lint/Syntax: else without rescue is useless
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
  else
  ^^^^
foo.rb:12:1: E: Lint/Syntax: unexpected token kEND
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
end
^^^
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ bundle exec rubocop -V
0.69.0 (using Parser 2.6.2.0, running on ruby 2.4.5 x86_64-darwin17)
```
(`rubocop-performance` version is `1.3.0`)

**Comment by tejasbubane** [comment]
@koic I was trying to fix this error and have a doubt. Both `FOO =~ re` and `FOO.=~(re)` produce the exact same AST:

```
 s(:send,
  s(:const, nil, :FOO), :=~,
  s(:send, nil, :re))
```

How can we differentiate between the two? without falling back to source string that is.
