### ISSUE TITLE
Add a contribution guide

### ISSUE THREAD

**Issue by composerinteralia** [rubocop-hq/rubocop-performance#6]
I would like to get a contribution guide in soon. I imagine it will look basically like https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md

We will then want to link to the guide from the README.

We probably also want to set up the changelog and add this https://github.com/rubocop-hq/rubocop/blob/master/.gitattributes

**Comment by koic** [comment]
Contribution guide has been added by #32.
