### ISSUE TITLE
Performance Count Cop does not work

### ISSUE THREAD

**Issue by enthusiasmus** [rubocop-hq/rubocop-performance#69]
-------

## Expected behavior

I am expecting offenses for 

```
        [1, 2, 3].select { |e| e > 2 }.size
        [1, 2, 3].reject { |e| e > 2 }.size
        [1, 2, 3].select { |e| e > 2 }.length
        [1, 2, 3].reject { |e| e > 2 }.length
```

as seen in `https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/count.rb`

## Actual behavior

I don't receive offenses

## Steps to reproduce the problem

file foobar.rb with 

```
# frozen_string_literal: true

def foobar
  [1, 2, 3].select { |e| e > 2 }.size
  [1, 2, 3].reject { |e| e > 2 }.size
  [1, 2, 3].select { |e| e > 2 }.length
  [1, 2, 3].reject { |e| e > 2 }.length
end
```
executing rubocop performance via `rubocop --require rubocop-performance foobar.rb`

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.72.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-linux)

rubocop-performance version: 1.4.0
```

**Comment by koic** [comment]
Please set `SafeMode` of `Performance/Count` cop to `false` in rubocop.yml.

```yaml
Performance/Count:
  SafeMode: false
```

It is not working because `SafeMode` is `true` by default.
https://docs.rubocop.org/projects/performance/en/stable/cops_performance/#performancecount

## Related resources

- https://github.com/rubocop-hq/rubocop-performance/blob/v1.4.0/config/default.yml#L44-L48
- https://github.com/rubocop-hq/rubocop/pull/2862

**Comment by rrosenblum** [comment]
I came across this in the last day or two as well. Looking into it, I think the `SafeMode` on these cops has outlived its usefulness. `SafeMode` doesn't produce a single offense for either cop so it is the same as having it disabled by default. It is only documented inside of the `default.yml` file so user's don't know that the configuration exists. I think we would be better off disabling the cop by default, or changing it to be flagged as unsafe for auto-correction.

**Comment by enthusiasmus** [comment]
Thanks for the hint and reply!

**Comment by koic** [comment]
#72 has been released.
