### ISSUE TITLE
New cop: Use String#include? instead of String#match? with /literal-only-pattern/

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-performance#81]
## Is your feature request related to a problem? Please describe.

`String#include?` is faster than `String#match?` with a simple regexp.

https://gist.github.com/pocke/eeffeaa58ddcc35f862f6e1aca593b21
I wrote a few benchmarks, and I got the result.

The difference is small in simple cases (str1 and str2).
But there are clear differences if the string is long.

## Describe the solution you'd like

Add a cop to detect `String#match?` with simple regexp.
And I guess the cop also can detect `String#match` and `String#=~` if it is used as a condition.

## Describe alternatives you've considered

nothing

## Additional context

We already have Performance/StartWith and EndWIth. We can refer the cops to help to implement it.

**Comment by Drenmi** [comment]
> And I guess the cop also can detect String#match and String#=~ if it is used as a condition.

It's very hard to tell if people are using the global variables stored by `String#match`, but perhaps can include a configuration option for this?

**Comment by bbatsov** [comment]
Agreed. Generally the use of the globals has been on the decline, so I guess we can also advise people not to do it. I guess the only thing the globals have for them is that they are  more compact than the alternative.
